# Site settings 配置站点
title: '赛狗屁的技术空间 | 游戏 WEB 金融'
description: '欢迎来到赛狗屁的个人博客！这里是一个关于游戏开发、Web开发、经济学和金融的知识分享平台。'
keyword: '游戏开发，web开发，经济学，金融，赛狗屁, 博客，编程，技术'
url: 'https://saigoupi.github.io' # your host
title: '赛狗屁的技术空间 | 游戏 WEB 金融'
description: '欢迎来到赛狗屁的个人博客！这里是一个关于游戏开发、Web开发、经济学和金融的知识分享平台。'
keyword: '游戏开发，web开发，经济学，金融，赛狗屁, 博客，编程，技术'
url: 'https://saigoupi.github.io' # your host

# when build blog on server, if you don't need baseurl, you should leave this value blank.
# 在服务器上建站时，如果你不需要子域名，请将这一格留空
# if you're using GitHub Pages, set baseurl to your blog's .
# 如果你在使用 GitHub Pages, 请将 baseurl 设置为你的网址的子域名
# for example, if your site is "kaeyleo.github.io", then this url should leave blank.
# 例如，当你的域名是 "kaeyleo.github.io"  时，这个 url 需要留空
# but if your created a repo named "myblog", and the site is "kaeyleo.github.io/myblog", change baseurl to '/myblog'
# 但是，如果你创建了一个叫 "myblog" 的网站，此时网址会变成 "kaeyleo.github.io/myblog" ，这时再将 baseurl 设置为 '/myblog'
baseurl: ''
theme: jekyll-theme-h2o-ac

# Internalization 国际化
languages: ["zh-Hans", "zh-Hant", "en", "ja"]
default_lang: "zh-Hans"

# PWA
pwa:
  color: '#81BBFF'
  short_name: 'lisz'

# Navigation links
nav:
  home: '/'
  blog: '/blog/index.html'
  archives: '/archives.html'
  tags: '/tags.html'
  about:   
#    logs: '/logs.html'
#    tos: '/tos.html'
    RSS: '/feed.xml'
#    CV: '/cv.html'
    links: '/links.html'

# Gray for the whole site 全站灰色
gray: false

# Formats
# 时间格式（Time format）：0 -- 2022-04-29    1 -- 29 Apr 2022   2 -- 2022年4月29日
formats:
  time: 0   

# Favicon
favicon: "/favicon.ico"

# Author 配置博主信息
author: '赛狗屁'
nickname: 'SAIGOUPI'
bio: '游戏行业老兵 | Web开发新手 | 金融学徒'
avatar: '/assets/img/profile.webp'

# Search
search: true

# Night mode
nightMode: false

# Comments 评论功能
comments:
  disqus: false
  disqus_url: 'https://liaokeyu.disqus.com/embed.js'
  waline: false
  waline_url: 'https://h2o-ac-waline.vercel.app'

# MathJax 公式支持 by Ray-Eldath
mathjax: true

#### 文章最近更新时间自动更新
github:
  enabled: true                       # 是否开启
  owner: SAIGOUPI                      # Github 命名空间，用户名或组织名
  repository: saigoupi.github.io     # 项目名
toc: true  # 是否开启文章页目录导航
# Share
social-share: true
social-share-items: ['wechat', 'twitter']

# theme color 主题皮肤
theme-color: 'default'  # pink or default

# Post header background patterns (when the post no cover): circuitBoard, overlappingCircles, food, glamorous, ticTacToe, seaOfClouds
postPatterns: 'circuitBoard'

# SNS settings 配置社交网站
# url: email, weibo, zhihu, twitter, instagram, juejin, github, douban, facebook, dribble, uicn, jianshu, medium, linkedin
sns:
  github: 'https://github.com/SAIGOUPI'
  twitter: 'https://x.com/betterthanshits'
  cnblogs: 'https://www.cnblogs.com/saigoupi/'

# Links 友情链接
links:
  'H2O主题配置说明': 'https://h2o-ac-doc.lisz.me/intro/quickstart.html'

# Beian 备案号
beian: ''

# CC License
cclicense: true

# CNZZ Analytics
# cnzz: 1234567891
cnzz: 

# Busuanzi Analytics
busuanzi: true

# Umami Analytics
umami:
  status: 
  id: 
  js: 

# Google Analytics
# google_analytics: UA-XXXXXXXXX-X
google_analytics: 

# Google Search
google_search: 

#### 站内搜索
search: true

#### 站内搜索
search: true

# Tags 设置标签
recommend-tags: true # whether or not display recommend-tags on the sidebar
recommend-condition-size: 12 # a tag will be recommended if the size of it is more than this value

# Build settings
pagination:
  enabled: true
  per_page: 10
# paginate: 10
# paginate_path: 'blog/page:num'

# Markdown
markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM
prism:
  theme:
  line_numbers: true

# RSS
RSS: true

# Permalink
# See: https://github.com/kaeyleo/jekyll-theme-H2O/issues/35
permalink: /:categories/:title.html

# TOC
toc: true

# Mermaid
mermaid: true

# Webpusher
webpusher: false

# Foreverblog
foreverblog: true

# Wormhole
wormhole: true

# NotByAI
notbyAI: true

# Footer
footer:
  since: 2025

# Alive time
alivetime: true
alivestart: "7/26/2025"
supports:
  upyun: false              # 又拍云
  webify: false            # 腾讯云 Webify
badges:  # 其他徽章
  netlify: false            # Netlify
  vercel: false             # Vercel
  cloudflare: false         # Cloudfalre
  foreverblog: false        # Foreverblog
  wormhole: false           # Wormhole
  travelling: false         # Travelling
  notbyAI: false            # NotByAI